# Generated by Django 5.1 on 2024-08-29 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherhistory',
            name='subscription',
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
