# Generated by Django 5.1 on 2024-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_remove_weatherhistory_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherhistory',
            name='icon',
            field=models.CharField(null=True),
        ),
    ]
