# Generated by Django 5.1 on 2024-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_weatherhistory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherhistory',
            name='condition',
            field=models.CharField(null=True),
        ),
    ]
