# Generated by Django 5.1 on 2024-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_weatherhistory_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
