# Generated by Django 5.1 on 2024-08-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
